## Python for Data Analysis Chapter5

In [2]:
import numpy as np
import pandas as pd

In [3]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [4]:
arr[0]

array([0., 1., 2., 3.])

In [5]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [6]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns=list('bde'),
                    index=['utah','ohio','texas','oregon'])
series = frame.iloc[0]

In [7]:
frame

b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [8]:
series

b    0.0
d    1.0
e    2.0
Name: utah, dtype: float64

In [9]:
frame - series

b    d    e
utah    0.0  0.0  0.0
ohio    3.0  3.0  3.0
texas   6.0  6.0  6.0
oregon  9.0  9.0  9.0

In [13]:
series2 = pd.Series(range(3),index=['b','e','f'])

In [14]:
frame + series2

b   d     e   f
utah    0.0 NaN   3.0 NaN
ohio    3.0 NaN   6.0 NaN
texas   6.0 NaN   9.0 NaN
oregon  9.0 NaN  12.0 NaN

In [15]:
series3 = frame['d']

In [16]:
frame.sub(series3,axis='index')

b    d    e
utah   -1.0  0.0  1.0
ohio   -1.0  0.0  1.0
texas  -1.0  0.0  1.0
oregon -1.0  0.0  1.0

정렬과 순위

In [17]:
obj = pd.Series(range(4), index=list('dabc'))

In [18]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [19]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [21]:
obj.sort_index(ascending = False)

d    0
c    3
b    2
a    1
dtype: int64

In [22]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [23]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [24]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [26]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

상관관계와 공분산

In [27]:
conda install pandas-datareader

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\exem\anaconda3

  added / updated specs:
    - pandas-datareader


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.12.0               |   py39haa95532_0        14.5 MB
    pandas-datareader-0.10.0   |     pyhd3eb1b0_0          71 KB
    ------------------------------------------------------------
                                           Total:        14.5 MB

The following NEW packages will be INSTALLED:

  pandas-datareader  pkgs/main/noarch::pandas-datareader-0.10.0-pyhd3eb1b0_0

The following packages will be UPDATED:

  conda                               4.10.3-py39haa95532_0 --> 4.12.0-py39haa95532_0




conda-4.12.0         | 14.5 MB   |            |   0% 
conda-4.12.0         | 14.5 MB   | 3          |   3% 
conda-4.12.0         | 14.5 MB   | ####       |  40% 
conda-4.12.0    

In [30]:
import pandas_datareader.data as web
all_data = {ticker:web.get_data_yahoo(ticker)
           for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker:data['Adj Close']
                     for ticker,data in all_data.items()})
volume = pd.DataFrame({ticker:data['Volume']
                      for ticker,data in all_data.items()})

In [31]:
returns = price.pct_change()

In [32]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-03-29  0.019134  0.003575  0.015159  0.009158
2022-03-30 -0.006650  0.001440 -0.004914 -0.004227
2022-03-31 -0.017776 -0.015969 -0.017683 -0.020996
2022-04-01 -0.001718  0.001000  0.003600  0.007522
2022-04-01  0.000000  0.000000  0.000000  0.000000

In [33]:
returns['MSFT'].corr(returns['IBM'])

0.48168952263472925

In [34]:
returns['MSFT'].cov(returns['IBM'])

0.00014403284292424027

In [35]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.429602  0.746059  0.667216
IBM   0.429602  1.000000  0.481690  0.455943
MSFT  0.746059  0.481690  1.000000  0.786235
GOOG  0.667216  0.455943  0.786235  1.000000

In [36]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000381  0.000140  0.000260  0.000229
IBM   0.000140  0.000281  0.000144  0.000135
MSFT  0.000260  0.000144  0.000318  0.000247
GOOG  0.000229  0.000135  0.000247  0.000310

In [37]:
returns.corrwith(returns.IBM)

AAPL    0.429602
IBM     1.000000
MSFT    0.481690
GOOG    0.455943
dtype: float64

## Python for Data Analysis Chapter6

### 데이터 로딩과 저장, 파일 형식

read_csv() 옵션 중 names를 통해 행이름 지정, index_col을 통해 인덱스 이름 지정

파일을 여러 조각으로 나누어서 읽으려면 chunksize 옵션으로 로우의 개수를 조정

to_csv('.csv') csv 파일 생성하기

## Python for Data Analysis Chapter7

### 데이터 정제 및 준비

In [42]:
string_data = pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [43]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [44]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [45]:
string_data[0]=None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [46]:
from numpy import nan as NA

In [47]:
data = pd.Series([1,NA,3.5,NA,7])

In [48]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [49]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [50]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

#### dropna(how='all') 모두 NA 값인 로우만 제외

#### 결측치 채우기

In [52]:
df = pd.DataFrame(np.random.randn(7,3))

In [53]:
df

0         1         2
0 -1.468318  1.280779  0.779907
1 -1.330239  0.469270  1.277799
2  0.028310  0.379479  0.026148
3  0.682059  0.191369 -0.374514
4  1.048745 -0.823060  0.171758
5  0.183813 -0.454033  1.151016
6  0.544000  0.317203  0.012116

In [54]:
df.iloc[:4,1]=NA
df.iloc[:2,2]=NA

In [55]:
df

0         1         2
0 -1.468318       NaN       NaN
1 -1.330239       NaN       NaN
2  0.028310       NaN  0.026148
3  0.682059       NaN -0.374514
4  1.048745 -0.823060  0.171758
5  0.183813 -0.454033  1.151016
6  0.544000  0.317203  0.012116

In [56]:
df.dropna()

0         1         2
4  1.048745 -0.823060  0.171758
5  0.183813 -0.454033  1.151016
6  0.544000  0.317203  0.012116

In [57]:
df.dropna(thresh=2) ### thresh = n n개가 있는 행 출력

0         1         2
2  0.028310       NaN  0.026148
3  0.682059       NaN -0.374514
4  1.048745 -0.823060  0.171758
5  0.183813 -0.454033  1.151016
6  0.544000  0.317203  0.012116

In [62]:
df.fillna(0)

0         1         2
0 -1.468318  0.000000  0.000000
1 -1.330239  0.000000  0.000000
2  0.028310  0.000000  0.026148
3  0.682059  0.000000 -0.374514
4  1.048745 -0.823060  0.171758
5  0.183813 -0.454033  1.151016
6  0.544000  0.317203  0.012116

In [63]:
df.fillna({1:0.5,2:0})

0         1         2
0 -1.468318  0.500000  0.000000
1 -1.330239  0.500000  0.000000
2  0.028310  0.500000  0.026148
3  0.682059  0.500000 -0.374514
4  1.048745 -0.823060  0.171758
5  0.183813 -0.454033  1.151016
6  0.544000  0.317203  0.012116

fillna는 inplace=True 옵션으로 기존 객체를 변경 가능 

중복 제거하기

duplicated() 각 로우가 중복인지 아닌지 알려주는 불리언 값 반환

drop_duplicates() keep='last'옵션을 사용하면 마지막값을 남김

###### data.replace(-999,np.nan) 값 치환

rename 이름 바꾸기

In [66]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100]

In [67]:
cats = pd.cut(ages,bins)

In [68]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [69]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

np.random.permutation(5) # 특정 갯수의 램덤 배열 생성

## Python for Data Analysis Chapter8

### 데이터 준비하기: 조인, 병합, 변형

In [70]:
data = pd.Series(np.random.randn(9),
                index=[['a','a','a','b','b','c','c','d','d'],
                      [1,2,3,1,3,1,2,2,3]])

In [71]:
data

a  1   -0.766209
   2    0.505195
   3   -2.593979
b  1   -0.095304
   3   -1.205832
c  1    0.200304
   2    1.144094
d  2   -1.151246
   3    0.868654
dtype: float64

In [72]:
data.loc[:,2]

a    0.505195
c    1.144094
d   -1.151246
dtype: float64

In [73]:
data.unstack() ###데이터를 새롭게 배열

1         2         3
a -0.766209  0.505195 -2.593979
b -0.095304       NaN -1.205832
c  0.200304  1.144094       NaN
d       NaN -1.151246  0.868654

In [74]:
data.unstack().stack()

a  1   -0.766209
   2    0.505195
   3   -2.593979
b  1   -0.095304
   3   -1.205832
c  1    0.200304
   2    1.144094
d  2   -1.151246
   3    0.868654
dtype: float64

names 로 각 계층의 이름 입력 가능

계층의 순서를 바꾸고 정렬하기
swaplevel()

In [75]:
frame = pd.DataFrame({'a':range(7),'b':range(7,0,-1),
                     'c':['one','one','one','two','two','two','two'],
                     'd':[0,1,2,0,1,2,3]})

In [76]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [77]:
frame2 = frame.set_index(['c','d'])

In [78]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [79]:
frame.set_index(['c','d'],drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

reset_index 는 set_index의 반대

In [80]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

데이터 병합 함수 merge , join

##### 축따라 이어붙이기

In [81]:
arr = np.arange(12).reshape((3,4))

In [82]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
np.concatenate([arr,arr], axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [85]:
df1 = pd.DataFrame(np.random.randn(3,4),columns=['a','b','c','d'])
df2 = pd.DataFrame(np.random.randn(2,3),columns=['b','d','a'])

In [86]:
df1

a         b         c         d
0 -1.804031 -0.345756 -0.554477 -0.637576
1 -0.213770  0.085799 -0.431539 -0.908378
2 -0.531912  1.588239 -0.447705 -0.250691

In [87]:
df2

b         d         a
0 -1.469707  0.179198 -0.220541
1 -0.420771  0.073489 -1.720317

In [88]:
pd.concat([df1,df2])

a         b         c         d
0 -1.804031 -0.345756 -0.554477 -0.637576
1 -0.213770  0.085799 -0.431539 -0.908378
2 -0.531912  1.588239 -0.447705 -0.250691
0 -0.220541 -1.469707       NaN  0.179198
1 -1.720317 -0.420771       NaN  0.073489

In [89]:
pd.concat([df1,df2],ignore_index=True)

a         b         c         d
0 -1.804031 -0.345756 -0.554477 -0.637576
1 -0.213770  0.085799 -0.431539 -0.908378
2 -0.531912  1.588239 -0.447705 -0.250691
3 -0.220541 -1.469707       NaN  0.179198
4 -1.720317 -0.420771       NaN  0.073489

넓은 형식에서 긴 형식으로 피벗하기

In [91]:
df = pd.DataFrame({'key':['foo','bar','baz'],
                  'A':[1,2,3],
                  'B':[4,5,6],
                  'C':[7,8,9]})

In [92]:
df

key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [93]:
melted = pd.melt(df,['key'])

In [94]:
melted

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [95]:
reshaped = melted.pivot('key','variable','value')

In [96]:
reshaped

variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [97]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [98]:
pd.melt(df,id_vars=['key'],value_vars=['A','B'])

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [99]:
pd.melt(df,value_vars=['A','B','C'])

variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9

In [100]:
pd.melt(df,value_vars=['key','A','B'])

variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6