## Python for Data Analysis Chapter2

In [4]:
c = """
여러 줄에 걸친 문자열은
"""

In [5]:
c

'\n여러 줄에 걸친 문자열은\n'

In [6]:
c.count('\n')

2

format

In [7]:
template = '{0:.2f} {1:s} are worth US${2:d}'

In [10]:
template.format(4.2556,'tomato',2)

'4.26 tomato are worth US$2'

In [15]:
bool(3)

True

None 은 예약어가 아니라 NoneType의 유일한 인스턴스

datetime 모듈

In [16]:
from datetime import datetime, date, time

In [17]:
dt = datetime(2011, 10, 29, 20, 30, 21)

In [18]:
dt.day

29

In [19]:
dt.minute

30

strftime 메서드는 datetime을 문자열로

strptime 문자역을 해석하여 datetime 객체로

### if문, for문, While문

In [21]:
for i in range(4):
    for j in range(4):
        if j>i:
            break
        print(i,j)

0 0
1 0
1 1
2 0
2 1
2 2
3 0
3 1
3 2
3 3


In [22]:
x = 256
total = 0
while x>0:
    if total > 500:
        break
    total += x
    x = x//2

In [28]:
total

504

삼항표현식

In [29]:
x=5
'non-negtive' if x >=0 else 'negative'

'non-negtive'

## Python for Data Analysis Chapter3

#### 내장 자료구조, 함수, 파일

튜플: 튜플에 저장된 객체는 변경이 가능하지만 한 번 생성되면 각 슬록에 저장된 객체를 변경하는 건 불가능

In [31]:
tup = ('foo','bar','baz')
b_list = list(tup)
b_list

['foo', 'bar', 'baz']

In [32]:
b_list.append('dwarf')

In [33]:
b_list

['foo', 'bar', 'baz', 'dwarf']

insert 메서드를 사용해 특정위치에 값 추가

In [34]:
b_list.insert(1,'red')

In [35]:
b_list

['foo', 'red', 'bar', 'baz', 'dwarf']

pop 메서드 특정 위치의 값을 반환하고 해당 값을 리스트에서 삭제

remove 젤 앞에꺼 하나만 제거

리스트 이어 붙이기 +, extend

In [36]:
seq = [7,2,3,7,5,6,0,1]
seq[3:4] = [6,3]
seq

[7, 2, 3, 6, 3, 5, 6, 0, 1]

In [37]:
seq[:5]

[7, 2, 3, 6, 3]

In [39]:
seq[3:]

[6, 3, 5, 6, 0, 1]

In [40]:
seq[-4:]

[5, 6, 0, 1]

In [42]:
seq[-6:-2]

[6, 3, 5, 6]

ZIP

reversed 역순

#### 사전(dict)

In [43]:
empyt_dict = {}

In [44]:
d1 = {'a': 'some value','b' : [1,2,3,4]}

In [45]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [49]:
d1[7] = 'an integer'

In [50]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [51]:
d1['b']

[1, 2, 3, 4]

In [52]:
'b' in d1

True

In [53]:
d1[5] = 'some value'

In [54]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 5: 'some value'}

In [55]:
d1['dummy'] = 'another value'

In [56]:
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 5: 'some value',
 'dummy': 'another value'}

In [58]:
del d1[5]

In [59]:
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 'dummy': 'another value'}

In [60]:
ret = d1.pop('dummy')

In [61]:
ret

'another value'

In [62]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

### 중첩된 리스트 표기법

In [63]:
all_data = [['john','Emily','Michael','Mary','Steven'],
           ['Maria','Juan', 'Javier', 'Natalia','Pilar']]

In [66]:
names_of_interest = []
for names in all_data:
    enough_es = [name for name in names if name.count('e')>=2]
    names_of_interest.extend(enough_es)

In [68]:
names_of_interest

['Steven']

In [69]:
result = [name for names in all_data for name in names if name.count('e')>=2]

In [70]:
result

['Steven']

제너레이터

## Python for Data Analysis Chapter4

NumPy 기본: 배열과 벡터 연산

In [71]:
import numpy as np

In [72]:
data = np.random.randn(2,3)

In [73]:
data

array([[ 1.69828855,  0.00252179,  0.29935186],
       [-0.4529957 ,  0.55085325, -0.39348775]])

In [74]:
data.shape

(2, 3)

In [75]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [76]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [78]:
np.empty((2,3,2))

array([[[1.09527512e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.33511018e-306, 9.13854877e-043]],

       [[4.75192509e-037, 6.34899646e-066],
        [1.22313769e+161, 1.69061817e-052],
        [2.17773107e-076, 1.58837900e-076]]])

In [79]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
arr1.astype(np.int32)

array([6, 7, 8, 0, 1])